=== Szarlotka/XML/collection.dtd
<!ELEMENT collection (dvd|cd)* >

<!ELEMENT cd (title, artiste , year?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT artiste (pseudo,fName, lName)>
<!ELEMENT pseudo (#PCDATA)>
<!ELEMENT fName (#PCDATA)>
<!ELEMENT lName (#PCDATA)>
<!ELEMENT year (#PCDATA)>

<!ATTLIST cd id ID #REQUIRED>
<!ATTLIST cd style (unknown | rock | rap | blues | rnb | funk) "unknown">

<!ELEMENT dvd (title, year)>

<!ATTLIST dvd ref ID #REQUIRED>
<!ATTLIST dvd type (movie | report | cartoon | animated-film) "movie">

=== Szarlotka/XML/exo1_mediateque.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE collection SYSTEM "collection.dtd">
<collection>
    <cd id="c01">
        <title>Soundtrack from Twin Peaks</title>
        <artiste>
            <pseudo>AB</pseudo>
            <fName>Angelo</fName>
            <lName>Badalamenti</lName>
        </artiste>
        <year>1990</year>
    </cd>

    <dvd ref="d01" type="movie">
        <title>Rogue One</title>
        <year>2016</year>
    </dvd>
</collection>
