=== Szarlotka/XML/exo2_bank.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT bank (list-of-accounts, set_of_customers, set-of-customers_accounts)>

<!ELEMENT list-of-accounts (savings_account_list, checking_account_list)>
<!ELEMENT savings_account_list (savings_account)*>
<!ELEMENT savings_account (balance)>
<!ELEMENT balance (#PCDATA)>
<!ATTLIST savings_account id ID #REQUIRED>
<!ATTLIST savings_account interest CDATA #REQUIRED>
<!ELEMENT checking_account_list (checking_account)*>
<!ELEMENT checking_account (balance)>
<!ATTLIST checking_account id ID #REQUIRED>

<!ELEMENT set_of_customers (customer)*>
<!ELEMENT customer (name, address)>
<!ELEMENT name (#PCDATA) >
<!ELEMENT address (#PCDATA) >
<!ATTLIST customer id ID #REQUIRED>

<!ELEMENT set-of-customers_accounts (customer_account)*>
<!ATTLIST customer_account c_id IDREF #REQUIRED
                           ac_id IDREF #REQUIRED>

=== Szarlotka/XML/bank_init.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bank SYSTEM "exo2_bank.dtd">
<bank>
    <list-of-accounts>
        <savings_account_list>
            <savings_account id="a1" interest="0.03">
                <balance>2500</balance>
            </savings_account>
            <savings_account id="a2" interest="0.03">
                <balance>15075</balance>
            </savings_account>
        </savings_account_list>
        <checking_account_list>
            <checking_account id="a3">
                <balance>4025</balance>
            </checking_account>
            <checking_account id="a4">
                <balance>-125</balance>
            </checking_account>
            <checking_account id="a5">
                <balance>325</balance>
            </checking_account>
        </checking_account_list>
    </list-of-accounts>
    <set_of_customers>
        <customer id="c1">
            <name>Ben Richerdson</name>
            <address>Park Drive 2</address>
        </customer>
        <customer id="c2">
            <name>Marc Wretcher</name>
            <address>Mill Drive 75</address>
        </customer>
        <customer id="c3">
            <name>Angel Steady</name>
            <address>Lake Sight 15</address>
        </customer>
    </set_of_customers>
    <set-of-customer_accounts>
        <customer_account c_id="c1" ac_id="a2"/>
        <customer_account c_id="c1" ac_id="a3"/>
        <customer_account c_id="c2" ac_id="a4"/>
        <customer_account c_id="c3" ac_id="a1"/>
        <customer_account c_id="c3" ac_id="a5"/>
    </set-of-customer_accounts>
</bank>
